import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft,ArrowUpRight} from 'lucide-react';
import {articles} from '../articles';
import {Shell} from '../../site';
import {IpAtmos} from '../../inner/kit';
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const article=articles.find(a=>a.slug===slug);return {title:article?`${article.title} — Nakama Resources`:'Note not found — Nakama',description:article?.description};}
export default async function ArticlePage({params}:Props){const {slug}=await params;const a=articles.find(a=>a.slug===slug);if(!a)notFound();const next=articles[(articles.indexOf(a)+1)%articles.length];return <Shell className="article-page shell-cinema ip-page ip-article-page"><IpAtmos tone="teal"/><article><header className="article-heading page-width"><Link className="back-link" href="/resources#articles"><ArrowLeft size={16}/>Resources</Link><div className="article-meta"><span>{a.category}</span><span>{a.readTime}</span></div><h1>{a.title}</h1><p>{a.description}</p><div className="article-byline"><span className="byline-monogram">n.</span><span>Nakama Growth<small>Perspectives & practice</small></span></div></header><div className="article-body-layout page-width"><aside><span className="eyebrow">In this note</span><nav>{a.sections.map((s,i)=><a href={`#part-${i+1}`} key={s.heading}>{s.heading}</a>)}</nav></aside><div className="article-body">{a.sections.map((s,i)=><section id={`part-${i+1}`} key={s.heading}><span className="article-part">0{i+1}</span><h2>{s.heading}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}<p className="article-endnote">A note on our approach, from the Nakama team.</p></div></div></article><Link href={`/journal/${next.slug}`} className="next-article page-width"><div><span className="eyebrow">Keep reading</span><h2>{next.title}</h2></div><ArrowUpRight size={27}/></Link></Shell>}
